class ZCL_SCABSRC_TOKEN definition
  public
  create public .

public section.

  interfaces ZIF_SCABSRC_TOKEN .

  aliases GET_ALL_FIELDS
    for ZIF_SCABSRC_TOKEN~GET_ALL_FIELDS .
  aliases GET_STATEMENT
    for ZIF_SCABSRC_TOKEN~GET_STATEMENT .

  methods CONSTRUCTOR
    importing
      !SCABSRC type ref to ZCL_SCABSRC
      !INDEX type I .
protected section.
private section.

  data INDEX type SYTABIX .
  data SCABSRC type ref to ZCL_SCABSRC .
ENDCLASS.



CLASS ZCL_SCABSRC_TOKEN IMPLEMENTATION.


  method CONSTRUCTOR.

    ME->INDEX = INDEX.
    ME->SCABSRC = SCABSRC.

  endmethod.


  method ZIF_SCABSRC_TOKEN~GET_ALL_FIELDS.

    READ TABLE SCABSRC->LT_STOKESX INDEX INDEX INTO TOKEN.

  endmethod.


  method ZIF_SCABSRC_TOKEN~GET_STATEMENT.

    FIELD-SYMBOLS <LS_SSTRUC> TYPE SSTRUC.
    FIELD-SYMBOLS <LS_STATEMENT> TYPE ZCL_SCABSRC=>TY_IS_STATEMENT_BY_FROM.

    IF SCABSRC->AIT_STATEMENT_BY_FROM[] IS INITIAL.
      SCABSRC->CALCULATE_STATEMENT_BY_FROM( ).
    ENDIF.
    READ TABLE SCABSRC->AIT_STATEMENT_BY_FROM ASSIGNING <LS_STATEMENT>
          WITH KEY FROM = INDEX
          BINARY SEARCH.
    IF SY-SUBRC = 4.
      READ TABLE SCABSRC->AIT_STATEMENT_BY_FROM ASSIGNING <LS_STATEMENT> INDEX SY-TABIX.
    ELSEIF SY-SUBRC = 8.
      READ TABLE SCABSRC->AIT_STATEMENT_BY_FROM ASSIGNING <LS_STATEMENT> INDEX SY-TFILL.
    ENDIF.
    IF SY-SUBRC = 0.
      CREATE OBJECT STATEMENT TYPE ZCL_SCABSRC_STATEMENT
        EXPORTING
          SCABSRC = SCABSRC
          INDEX   = <LS_STATEMENT>-INDEX.
    ENDIF.

  endmethod.


ENDCLASS.
