class ZCL_SCABSRC_STATEMENTS definition
  public
  create public .

public section.

  interfaces ZIF_SCABSRC_STATEMENTS .

  aliases ADD_STATEMENT
    for ZIF_SCABSRC_STATEMENTS~ADD_STATEMENT .
  aliases ADD_STATEMENTS
    for ZIF_SCABSRC_STATEMENTS~ADD_STATEMENTS .
  aliases FULL_TEXT_SEARCH
    for ZIF_SCABSRC_STATEMENTS~FULL_TEXT_SEARCH .
  aliases GET_NEXT
    for ZIF_SCABSRC_STATEMENTS~GET_NEXT .

  methods CONSTRUCTOR
    importing
      !SCABSRC type ref to ZCL_SCABSRC
      !FROM type I default 0
      !TO type I default 0 .
protected section.
private section.

  types:
    BEGIN OF TY_IS_RANGE,
              FROM  TYPE SYTABIX,
              TO    TYPE SYTABIX,
            END OF TY_IS_RANGE .

  data FROM type SYTABIX .
  data TO type SYTABIX .
  data NEXT type SYTABIX .
  data NEXT2 type SYTABIX .
  data:
    TAB_RANGE TYPE TABLE OF TY_IS_RANGE .
  data SCABSRC type ref to ZCL_SCABSRC .
ENDCLASS.



CLASS ZCL_SCABSRC_STATEMENTS IMPLEMENTATION.


  method ZIF_SCABSRC_STATEMENTS~ADD_STATEMENT.

    DATA RANGE TYPE TY_IS_RANGE.
    RANGE-FROM  = INDEX.
    RANGE-TO    = INDEX.
    APPEND RANGE TO TAB_RANGE.

  endmethod.


  method ZIF_SCABSRC_STATEMENTS~ADD_STATEMENTS.

    DATA RANGE TYPE TY_IS_RANGE.
    RANGE-FROM  = FROM.
    RANGE-TO    = TO.
    APPEND RANGE TO TAB_RANGE.

  endmethod.


  method CONSTRUCTOR.

    ME->FROM = FROM.
    ME->TO   = TO.
    ME->NEXT = 0.
    ME->SCABSRC = SCABSRC.

  endmethod.


  method ZIF_SCABSRC_STATEMENTS~FULL_TEXT_SEARCH.

    DATA LO_STATEMENT TYPE REF TO ZIF_SCABSRC_STATEMENT.
    DATA INDEX TYPE SYTABIX.
    DATA FULL_STATEMENT TYPE STRING.
    DATA TAB_STMNT_INDEX TYPE TABLE OF SYTABIX.
    DATA TAB_FULL_TEXT TYPE TABLE OF STRING.
    DATA LS_SSTMNT TYPE SSTMNT.
    FIELD-SYMBOLS <LS_STOKESX> TYPE STOKESX.
    DATA LT_MATCH TYPE MATCH_RESULT_TAB.
    FIELD-SYMBOLS <LS_MATCH> TYPE MATCH_RESULT.

    LO_STATEMENT = GET_NEXT( ).
    WHILE LO_STATEMENT IS BOUND.
      INDEX = LO_STATEMENT->GET_INDEX( ).
      LS_SSTMNT = LO_STATEMENT->GET_ALL_FIELDS( ).
      READ TABLE TAB_STMNT_INDEX WITH KEY TABLE_LINE = INDEX TRANSPORTING NO FIELDS.
      IF SY-SUBRC <> 0.
        APPEND INDEX TO TAB_STMNT_INDEX.
        CLEAR FULL_STATEMENT.
        LOOP AT SCABSRC->LT_STOKESX ASSIGNING <LS_STOKESX>
              FROM LS_SSTMNT-FROM
              TO   LS_SSTMNT-TO.
          IF FULL_STATEMENT IS INITIAL.
            FULL_STATEMENT = <LS_STOKESX>-STR.
          ELSE.
            CONCATENATE FULL_STATEMENT <LS_STOKESX>-STR INTO FULL_STATEMENT
                  SEPARATED BY SPACE.
          ENDIF.
        ENDLOOP.
        APPEND FULL_STATEMENT TO TAB_FULL_TEXT.
      ENDIF.
      LO_STATEMENT = GET_NEXT( ).
    ENDWHILE.

    FIND ALL OCCURRENCES OF REGEX REGEX IN TABLE TAB_FULL_TEXT RESULTS LT_MATCH.
    LOOP AT LT_MATCH ASSIGNING <LS_MATCH>.
      ...
    ENDLOOP.

  endmethod.


  method ZIF_SCABSRC_STATEMENTS~GET_NEXT.

    FIELD-SYMBOLS <RANGE> TYPE TY_IS_RANGE.
    IF FROM >= 1.
      IF NEXT = 0.
        NEXT = FROM.
      ENDIF.
      IF NEXT <= TO.
        CREATE OBJECT STATEMENT TYPE ZCL_SCABSRC_STATEMENT
          EXPORTING
            SCABSRC = SCABSRC
            INDEX   = NEXT.
        ADD 1 TO NEXT.
      ENDIF.
    ELSE.
      IF NEXT = 0.
        NEXT = 1.
        NEXT2 = 0.
      ENDIF.
      DO.
        READ TABLE TAB_RANGE ASSIGNING <RANGE> INDEX NEXT.
        IF SY-SUBRC <> 0.
          EXIT.
        ENDIF.
        IF NEXT2 = 0.
          NEXT2 = <RANGE>-FROM.
        ENDIF.
        IF NEXT2 <= <RANGE>-TO.
          CREATE OBJECT STATEMENT TYPE ZCL_SCABSRC_STATEMENT
            EXPORTING
              SCABSRC = SCABSRC
              INDEX   = NEXT2.
          ADD 1 TO NEXT2.
          EXIT.
        ELSE.
          ADD 1 TO NEXT.
          NEXT2 = 0.
        ENDIF.
      ENDDO.
    ENDIF.

  endmethod.


ENDCLASS.
