class ZCL_SCABSRC_SOURCE_UNIT definition
  public
  create public .

public section.

  interfaces ZIF_SCABSRC_SOURCE_UNIT .

  aliases GET_ALL_FIELDS
    for ZIF_SCABSRC_SOURCE_UNIT~GET_ALL_FIELDS .
  aliases GET_INVOKING_STATEMENT
    for ZIF_SCABSRC_SOURCE_UNIT~GET_INVOKING_STATEMENT .
  aliases GET_INVOKING_UNIT
    for ZIF_SCABSRC_SOURCE_UNIT~GET_INVOKING_UNIT .
  aliases GET_STATEMENTS
    for ZIF_SCABSRC_SOURCE_UNIT~GET_STATEMENTS .

  methods CONSTRUCTOR
    importing
      !SCABSRC type ref to ZCL_SCABSRC
      !INDEX type I .
protected section.
private section.

  data INDEX type SYTABIX .
  data SCABSRC type ref to ZCL_SCABSRC .
ENDCLASS.



CLASS ZCL_SCABSRC_SOURCE_UNIT IMPLEMENTATION.


  method CONSTRUCTOR.

    ME->INDEX = INDEX.
    ME->SCABSRC = SCABSRC.

  endmethod.


  method ZIF_SCABSRC_SOURCE_UNIT~GET_ALL_FIELDS.

    READ TABLE SCABSRC->LT_SLEVEL INDEX INDEX INTO SOURCE_UNIT.

  endmethod.


  method ZIF_SCABSRC_SOURCE_UNIT~GET_INVOKING_STATEMENT.


  endmethod.


  method ZIF_SCABSRC_SOURCE_UNIT~GET_INVOKING_UNIT.


  endmethod.


  method ZIF_SCABSRC_SOURCE_UNIT~GET_STATEMENTS.

    FIELD-SYMBOLS <LS_SLEVEL> TYPE SLEVEL.
    READ TABLE SCABSRC->LT_SLEVEL INDEX INDEX ASSIGNING <LS_SLEVEL>.
    IF SY-SUBRC = 0.
      CREATE OBJECT STATEMENTS TYPE ZCL_SCABSRC_STATEMENTS
        EXPORTING
          SCABSRC = SCABSRC
          FROM    = <LS_SLEVEL>-FROM
          TO      = <LS_SLEVEL>-TO.
    ENDIF.

  endmethod.


ENDCLASS.
